### ISSUE TITLE
Unable to RunSpecifiedTests despite test file included in package.xml manifest file

### ISSUE THREAD

**Issue by JasonFung6** [tiagonnascimento/sfdx-orgdev-build-deploy#11]
I'm getting the below error when deploying Apex class with the associated test class defined in my `package.xml` file.

Example manifest file:

```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
  <types>
    <members>MyApexClassTest</members>
    <members>MyApexClass</members>
    <name>ApexClass</name>
  </types>
  <version>50.0</version>
</Package>
```
The error I see in github actions log:

```
=== deploy ===
=== getApexTestClass ===
Error: ENOENT: no such file or directory, open '/classes/MyApexClass.cls'
```

**Comment by tiagonnascimento** [comment]
@manuelcortessf @manuelcortes15 - can you take a look into this if possible? Just let me know, else I can take a look. 

@JasonFung6 , thank you for reporting.

**Comment by JasonFung6** [comment]
@tiagonnascimento after looking at the repo source files I realised the default source path was not defined, i've created a PR to update the readme: #12 - it will be good if this default path is set in the JS files rather than having to define this in the .yaml

**Comment by tiagonnascimento** [comment]
@JasonFung6 , thank you for your contribution. I merged your PR and I'm adding the default value as suggested as well.
