### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by JasonFung6** [tiagonnascimento/sfdx-orgdev-build-deploy#13]
Is there a way to see what the code coverage is after running all local tests or running specified tests?

Is there also a way to specify _not_ to run any tests when deploying to a Sandbox?

**Comment by tiagonnascimento** [comment]
@JasonFung6 , I believe, in the past, the sfdx force:source:deploy command was returning the code coverage at the default log level (warm), it looks like now it's not returning anymore. You can always look at your own sandbox at Setup -> Deploy Status and check the coverage there though. 

About not running the tests, you can prepare your workflow and pass the parm deploy_testlevel: NoTestRun
