### ISSUE TITLE
On every deploy i got error 

### ISSUE THREAD

**Issue by g1b3r** [tiagonnascimento/sfdx-orgdev-build-deploy#9]
Hello 
When i using CLI everything its working fine but 
On every deploy using action i got error : 

Command executed: sfdx
With the following args: force:source:deploy,--wait,10,--manifest,manifest/package.xml,--targetusername,sfdc,--json,--testlevel,RunLocalTests
Having the following return: {
  "status": 1,
  "result": [
    {
      "error": "Unknown"
    }
  ],
  "name": "DeployFailed",
  "message": "Deploy failed.",
  "exitCode": 1,
  "actions": [],
  "commandName": "SourceDeployCommand",
  "data": [
    {
      "error": "Unknown"
    }
  ],
  "stack": "DeployFailed: Deploy failed.\n    at /usr/local/lib/sfdx/node_modules/salesforce-alm/dist/lib/source/sourceApiCommand.js:70:31\n    at async SourceDeployCommand.execLegacyCommand (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/ToolbeltCommand.js:149:29)\n    at async SourceDeployCommand.run (/usr/local/lib/sfdx/node_modules/salesforce-alm/dist/commands/force/source/deploy.js:32:16)\n    at async SourceDeployCommand._run (/usr/local/lib/sfdx/node_modules/@salesforce/command/lib/sfdxCommand.js:93:40)\n    at async Config.runCommand (/usr/local/lib/sfdx/node_modules/@oclif/config/lib/config.js:173:24)\n    at async Main.run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/main.js:27:9)\n    at async Main._run (/usr/local/lib/sfdx/node_modules/@oclif/command/lib/command.js:43:20)\n    at async Object.run (/usr/local/lib/sfdx/dist/cli.js:32:20)",
  "warnings": []
}

**Comment by tiagonnascimento** [comment]
Hi @g1b3r , did you already check on the action log what's going on? When I got these unknown error was always related with test cases failing. Get the entire execution log from the github action and look for Failure or Error, probably you will find more details.

**Comment by g1b3r** [comment]
Hi 

 

I already investigate issue i try to use in secrets USERNAME instead USERNAME_TI01 this is caused issue

**Comment by tiagonnascimento** [comment]
Great! You can use USERNAME as secret name, as long as you refer to the same variable name in the yml.
